_homepage:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
              
_acount:
    resource: "@AppBundle/Controller/AccountController.php"
    type:     annotation
  
_auth:
    resource: "@AppBundle/Controller/AuthController.php"
    type:     annotation
    
_aid:
    resource: "@AppBundle/Controller/AccessIDController.php"
    type:     annotation
    
_loc:
    resource: "@AppBundle/Controller/LocationController.php"
    type:     annotation
    
_iodev:
    resource: "@AppBundle/Controller/IODeviceController.php"
    type:     annotation

_schedule:
    resource: "@AppBundle/Controller/ScheduleController.php"
    type:     annotation
    
_ajax:
    resource: "@AppBundle/Controller/AjaxController.php"
    type:     annotation

    