<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class IODeviceChannel extends \AppBundle\Entity\IODeviceChannel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'channelNumber', 'iodevice', 'user', 'caption', 'type', 'function', 'param1', 'param2', 'param3');
        }

        return array('__isInitialized__', 'id', 'channelNumber', 'iodevice', 'user', 'caption', 'type', 'function', 'param1', 'param2', 'param3');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (IODeviceChannel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getChannelNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannelNumber', array());

        return parent::getChannelNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getCaption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaption', array());

        return parent::getCaption();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaption($caption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaption', array($caption));

        return parent::setCaption($caption);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function getIoDevice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIoDevice', array());

        return parent::getIoDevice();
    }

    /**
     * {@inheritDoc}
     */
    public function getFunction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFunction', array());

        return parent::getFunction();
    }

    /**
     * {@inheritDoc}
     */
    public function setFunction($function)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFunction', array($function));

        return parent::setFunction($function);
    }

    /**
     * {@inheritDoc}
     */
    public function getChannel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannel', array());

        return parent::getChannel();
    }

    /**
     * {@inheritDoc}
     */
    public function getParam1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParam1', array());

        return parent::getParam1();
    }

    /**
     * {@inheritDoc}
     */
    public function setParam1($param1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParam1', array($param1));

        return parent::setParam1($param1);
    }

    /**
     * {@inheritDoc}
     */
    public function getParam2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParam2', array());

        return parent::getParam2();
    }

    /**
     * {@inheritDoc}
     */
    public function setParam2($param2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParam2', array($param2));

        return parent::setParam2($param2);
    }

    /**
     * {@inheritDoc}
     */
    public function getParam3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParam3', array());

        return parent::getParam3();
    }

    /**
     * {@inheritDoc}
     */
    public function setParam3($param3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParam3', array($param3));

        return parent::setParam3($param3);
    }

}
